"""Coordinator Agent module for the Student Life OS multi-agent AI system.

This module contains the CoordinatorAgent class, which acts as the central router
directing user prompts to the correct specialized sub-agent.
"""
from typing import Union

from agents.research_agent import ResearchAgent
from agents.study_planner import StudyPlannerAgent


class CoordinatorAgent:
    """An agent that routes user queries to specialized sub-agents."""

    ROUTING_RULES = {
        "study_planner": ["study", "plan"],
        "research_agent": ["research", "search"],
        "memory_agent": ["save", "remember"],
    }

    def __init__(self) -> None:
        """Initializes the Coordinator Agent and its specialized sub-agents."""
        self.name: str = "Coordinator Agent"
        self.research_agent = ResearchAgent()
        self.study_planner = StudyPlannerAgent()

    def route_request(self, user_input: str) -> Union[str, dict]:
        """Routes the user's input to the correct specialized agent.

        Analyzes the text for key phrases and returns the identifier of the
        appropriate agent, or 'unknown' if no match is found.

        Args:
            user_input: The raw text prompt from the user.

        Returns:
            The response generated by the selected agent, or an error
            response if no suitable agent is found.
        """

        if not user_input or not isinstance(user_input, str):
            return "unknown"

        # Create a new variable for the cleaned input to avoid mutating parameters
        clean_input = user_input.strip().lower()

        # Check keywords for each agent
        for agent_id, keywords in self.ROUTING_RULES.items():
            if any(keyword in clean_input for keyword in keywords):

                if agent_id == "study_planner":
                    return self.study_planner.handle(user_input)

                if agent_id == "research_agent":
                    return self.research_agent.handle(user_input)

                if agent_id == "memory_agent":
                    return {
                        "status": "success",
                        "agent": "memory_agent",
                        "message": f"Memory feature triggered for: {user_input}"
                    }

        # fallback OUTSIDE loop (VERY IMPORTANT)
        return {
            "status": "error",
            "message": "No suitable agent found"
        }

if __name__ == "__main__":
    # Instantiate the agent and demonstrate routing behavior
    agent = CoordinatorAgent()

    # The expected output is shown next to each print statement for clarity
    print(agent.route_request("Help me plan my study for the AI Capstone Project"))  # Expected: Formatted study plan
    print(agent.route_request("research AI agents"))    # Expected: research_agent
    print(agent.route_request("save my notes"))          # Expected: memory_agent
    print(agent.route_request("What is the weather today?"))   # Expected: unknown

    
    